[package]
name = "acpi_client"
version = "0.1.0"
authors = ["ssnover95 <ssnover95@gmail.com>"]
edition = "2018"
description = "A library for parsing ACPI data from the Linux filesystem."
license = "MIT"

[dependencies]
